# This is a SecretProviderClass example using a service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kvfmiguelakslab" # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret        # object types: secret, key or cert
        - |
          objectName: secret2
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47" # the tenant ID of the KeyVault
